### ISSUE TITLE
安装axt-agent 安装不成功 -一直报OSError: [Errno 22] Invalid argument 

### ISSUE THREAD

**Issue by FeeLzheng** [openatx/atxserver2-android-provider#29]
报错信息：
[E 191022 17:27:05 main:263] Unknown error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "main.py", line 246, in device_watch
    await device.init()
  File "E:\program\atxserver2-android-provider\device.py", line 60, in init
    self._init_binaries()
  File "E:\program\atxserver2-android-provider\device.py", line 117, in _init_binaries
    zipfile_path=zipfile_path)
  File "E:\program\atxserver2-android-provider\device.py", line 132, in _push_stf
    dest_info = self._device.sync.stat(dest)
  File "C:\Users\74156\AppData\Local\Programs\Python\Python36-32\lib\site-packages\adbutils\__init__.py", line 423, in stat
    return FileInfo(mode, size, datetime.datetime.fromtimestamp(mtime),
OSError: [Errno 22] Invalid argument

手机 oppo  R11   adbutils版本是0.62的

**Comment by qugo9955** [comment]
window环境下，我也遇到这个问题，有没什么解决方案？

**Comment by qugo9955** [comment]
adb手动推送相关文件到手机上，可以解决此问题。比如：
adb -s c6caca92 push E:\PyWorkSpace\atxserver2-android-provider-master\vendor\stf-binaries-0.2.1\node_modules\minicap-prebuilt\prebuilt\arm64-v8a\lib\android-29\minicap /data/local/tmp
