### ISSUE TITLE
Unknown error: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by lijianxi** [openatx/atxserver2-android-provider#38]
``D:\atxserver2-android-provider\atxserver2-android-provider>python main.py --server 10.252.25.198:4000
[I 201103 10:42:31 main:299] Owner: None
[I 201103 10:42:31 main:314] ProviderURL: http://10.252.63.137:3500
>>> app-uiautomator.apk verison: 2.3.1
>>> app-uiautomator-test.apk verison: 2.3.1
[I 201103 10:42:31 heartbeat:139] WS receive: {"success": true, "id": "37373a92-1d7e-11eb-bfe6-0242ac120003"}
[D 201103 10:42:31 main:234] DeviceEvent(present=True, serial='6040b6f3', status='device')
[I 201103 10:42:31 device:57] Init device: 6040b6f3
[D 201103 10:42:31 device:85] [6040b6f3] sdk: 27, abi: arm64-v8a, abis: ['arm64-v8a', 'armeabi-v7a', 'armeabi']
[D 201103 10:42:31 device:132] [6040b6f3] already pushed stf-binaries-0.2.1/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-27/minicap.so
[D 201103 10:42:32 device:113] [6040b6f3] use atx-agent: atx-agent-armv7
[D 201103 10:42:32 device:132] [6040b6f3] already pushed atx-agent-armv7
[D 201103 10:42:32 device:151] [6040b6f3] already installed vendor/WhatsInput-1.0.apk
>>> app-uiautomator.apk verison: 2.3.1
>>> app-uiautomator-test.apk verison: 2.3.1
APKPath: vendor/app-uiautomator-2.3.1\app-uiautomator.apk
[D 201103 10:42:32 device:151] [6040b6f3] already installed vendor/app-uiautomator-2.3.1\app-uiautomator.apk
APKPath: vendor/app-uiautomator-2.3.1\app-uiautomator-test.apk
[D 201103 10:42:32 device:151] [6040b6f3] already installed vendor/app-uiautomator-2.3.1\app-uiautomator-test.apk
[D 201103 10:42:32 device:161] [6040b6f3] forward atx-agent
[D 201103 10:42:33 device:208] [6040b6f3] tcpproxy.js start *:20001 -> 20000
[E 201103 10:42:33 main:264] Unknown error: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "main.py", line 247, in device_watch
    await device.init()
  File "D:\atxserver2-android-provider\atxserver2-android-provider\device.py", line 62, in init
    await self._init_forwards()
  File "D:\atxserver2-android-provider\atxserver2-android-provider\device.py", line 162, in _init_forwards
    self._atx_proxy_port = await self.proxy_device_port(7912)
  File "D:\atxserver2-android-provider\atxserver2-android-provider\device.py", line 214, in proxy_device_port
    silent=True)
  File "D:\atxserver2-android-provider\atxserver2-android-provider\device.py", line 222, in run_background
    p = subprocess.Popen(*args, **kwargs)
  File "C:\Users\lijianxi\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\lijianxi\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Hellowlonewolf** [comment]
me too

**Comment by unit2006** [comment]
![image](https://user-images.githubusercontent.com/37095235/105274694-a426c580-5bd8-11eb-9dc6-b179fb7e989a.png)
1. 修改device.py：subprocess.Popen(*args, **kwargs) 修改为： p = subprocess.Popen(*args, **kwargs,shell=True)
2. 重新执行：python main.py --server 10.252.25.198:4000
