### ISSUE TITLE
同时连接两台设备失败

### ISSUE THREAD

**Issue by SunYang0** [openatx/atxserver2-android-provider#60]
[D 220120 10:47:44 device:161] [885bc9a2] forward atx-agent
[E 220120 10:47:44 main:264] Unknown error: unknown host service
Traceback (most recent call last):
  File "main.py", line 247, in device_watch
    await device.init()
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\device.py", line 62, in init
    await self._init_forwards()
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\device.py", line 162, in _init_forwards
    self._atx_proxy_port = await self.proxy_device_port(7912)
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\device.py", line 205, in proxy_device_port
    local_port = await self.adb_forward_to_any("tcp:" + str(device_port))
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\device.py", line 194, in adb_forward_to_any
    async for f in adb.forward_list():
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\asyncadb.py", line 176, in forward_list
    await conn.check_okay()
  File "D:\software\pycharm_workplace\PycharmProjects\atxserver2-android-provider\asyncadb.py", line 60, in check_okay
    raise AdbError(await self.read_string())
asyncadb.AdbError: unknown host service

手机上atx显示failed to connect to 127.0.0.1:7912

**Comment by SunYang0** [comment]
问题解决了，adb版本的问题，原来用的adb1.0.40，换成1.0.39就好了
